In [3]:
import numpy as np

## 標準入出力
https://qiita.com/kyuna/items/8ee8916c2f4e36321a1c

In [ ]:
n=int(input())  #数値入力 「N」だけの入力のとき
a,b=map(int, input().split())  #複数数値入力　「A B」みたいなスペース空いた入力のとき
c=list(map(int, input().split()))  #リスト入力 「a1 a2 a3 ...」みたいな配列のような入力のとき
s=[list(map(int,list(input()))) for i in range(h)]  # 二次元配列入力　二次元マップみたいな入力のとき
print(*c)  #リスト出力
for i in [['#','.','#'],['#','#','#']]:print(*i, sep='') #二次元リストで間を詰めたもの
#.#

for i in range(N):
    

In [ ]:
#複数行のとき
N = int(input())
A = list(map(int, input().split())) 
B = list(map(int, input().split())) 
C = list(map(int, input().split())) 

# ソート
https://qiita.com/suecharo/items/30f5d817da4c948c3be6

名称	平均計算時間	最悪計算時間	メモリ使用量	安定性
バブルソート	O(n2)O(n2)	O(n2)O(n2)	O(1)O(1)	安定
選択ソート	O(n2)O(n2)	O(n2)O(n2)	O(1)O(1)	安定ではない
挿入ソート	O(n2)O(n2)	O(n2)O(n2)	O(1)O(1)	安定
マージソート	O(nlogn)O(nlog⁡n)	O(nlogn)O(nlog⁡n)	O(n)O(n)	安定
クイックソート	O(nlogn)O(nlog⁡n)	O(n2)O(n2)	O(logn)O(log⁡n)	安定ではない
カウントソート	O(nk)O(nk)	O(n2k)O(n2k)	O(nk)O(nk)	安定ではない

## バブルソート n^2
横同士の大小を比較し、必要なくなるまで交換する  
左から順番に左右を比較する。左>右なら交換する  
https://wa3.i-3-i.info/word14886.html

In [9]:
arr=np.random.randint(1,100,size=6)
def bubble_sort(arr):
    change=True
    while change:
        change=False
        for i in range(len(arr)-1):
            if arr[i]>arr[i+1]:
                arr[i],arr[i+1]=arr[i+1],arr[i]
                change=True
    return arr
bubble_sort(arr)

array([18, 24, 48, 69, 92, 92])

###

## 選択ソート  
配列中の最小か最大を端に移動させていく。  
左端をとりあえずの最小と仮定してそれより小さい値を右側から探す。    
終わったら一個右にずらす.  
移動が一回なので、バブルソートより若干早い  
http://sevendays-study.com/algorithm/day5.html

In [12]:
#arr.__getitem__(3)==arr[3]

69

In [13]:
def sellect_sort(arr):
    for idx,ele in enumerate(arr):
        min_idx=min(range(idx,len(arr)),key=arr.__getitem__)
        arr[idx],arr[min_idx]=arr[min_idx],ele
    return arr
sellect_sort(arr)


array([18, 24, 48, 69, 92, 92])

## 挿入ソート
0,1番要素を比較し入れ替える。  
2番目の要素が一番目までの要素より小さい場合、正しい順に並ぶように挿入する。  
次は三番目、、、と繰り返す。  
左からだんだんと揃っていく。ほとんど揃っている場合は高速  
二分探索すると早い。

In [16]:
def insert_sort(arr):
    for i in range(1,len(arr)):
        j= i-1
        ele =arr[i]
        #現在の値より小さくなるところまで進んでいって
        #今までの要素をひとつずつずらす交換する
        while arr[j]>ele and j>=0:
            arr[j+1]=arr[j]
            j-=1
        arr[j+1]=ele
    return arr

insert_sort(arr)

array([18, 24, 48, 48, 48, 92])

### 二分挿入ソート
挿入するデータの前は整列が済んでいるという性質を生かして  
挿入する箇所を二分探索する

In [ ]:
import sys
#再起の上限を増やす
sys.setrecursionlimit(10 ** 7)
#ソートされていることが前提。
def binary_search(arr,low,hig,ele):
    #もう添字が同じになった場合
    if low==hig:
        if arr[low]>ele:
            return low
        else:
            return low+1
    #添字が逆転した場合
    elif low>high:
        return low
    
    mid =(low+high)//2
    #現在値が真ん中より大きい場合
    if arr[mid]<ele:
        #現在値＋１から最大値までで検索
        return binary_search(arr,mid +1,hig,ele)
    elif: arr[mid]>ele:
        return binary_search(arr,low,mid-1,ele)
    else:
        return mid

def insert_sort(arr):
    for i in range(1,len(arr)):
        ele=arr[i]
        idx=binary_search(arr,0,i-1,ele)
        #挿入している
        arr[:]=arr[:idx]+[ele]+arr[idx:i]+arr[i+1:]



## マージソート
分割を繰り返し、その後に順に結合していく。  
結合の過程でソートする。  
早いけどメモリを食う  

In [17]:
def merge_sort(arr):
    if len(arr)<=1:
        return arr
    mid = len(arr)//2
    #分割する
    left=arr[:mid]
    right=arr[mid:]

    #再起的に分割する
    left=merge_sort(left)
    right=merge_sort(right)

    return merge(left,right)

def merge(left,right):
    merged=[]
    l_i,r_i=0,0
    #比較して小さい方の先頭を順番に追加していく
    while l_i<len(left) and r_i <len(right):
        if left[l_i]<=right[r_i]:
            merged.append(left[l_i])
            l_i+=1
        else:
            merged.append(right[r_i])
            r_i +=1

    #上のWhileが終わった時のあまりを追加する
    if l_i<len(left):
        merged.extend(left[l_i:])
    if r_i <len(right):
        merged.extend(right[r_i:])
    return merged
merge_sort(arr)


[18, 24, 48, 48, 48, 92]

## クイックソート
基準値を決めて、そのその基準値から見て大小の2つの配列に分ける。  
分けたグループの中で再起的に同じ処理をする  
ある程度分割できたら別のアルゴリズムを使うと早い 
不安定かつ、メモリを多く使うが早い

In [18]:
def quick_sort(arr):
    left=[]
    right=[]
    if len(arr)<= 1:
        return arr
    ref=arr[0]
    ref_count=0
    for ele in arr:
        if ele<ref:
            left.append(ele)
        elif ele>ref:
            right.append(ele)
        else:
            ref_count+=1
    #左右に分けてソート
    left =  quick_sort(left)
    right =quick_sort(right)

    #結合。同じ奴はref_countで数を重ねる
    return left +[ref]*ref_count +right
quick_sort(arr)

[18, 24, 48, 48, 48, 92]

## カウントソート
それぞれの値の個数を数えていく  
defaultdictを使うと楽チン

In [20]:
def count_sort(arr):
    max_num=max(arr)
    min_num=min(arr)
    #要素の数だけ入れ物を用意する
    count=[0]*(max_num-min_num+1)
    for ele in arr:
        count[ele-min_num]+=1
        #ele...入れ物の現在の値のidx,cnt...何回繰り返す
    return [ele for ele,cnt in enumerate(count,start=min_num) for _ in range(cnt)]
count_sort(arr)

[18, 24, 48, 48, 48, 92]

## DFS,BFS
http://kannokanno.hatenablog.com/entry/2013/06/05/175503
https://pyteyon.hatenablog.com/entry/2019/03/01/211133

### DFS
1. 根ノードrootからスタート
1. 末端まで進めるまで進める
1. 末端に着いたらひとつ前に戻ってまだ進んでない分岐を進む
1. 進んでないところがあればもうひとつ前に戻る



In [27]:
graph1 = {
    'A' : ['B','S'],
    'B' : ['A'],
    'C' : ['D','E','F','S'],
    'D' : ['C'],
    'E' : ['C','H'],
    'F' : ['C','G'],
    'G' : ['F','S'],
    'H' : ['E','G'],
    'S' : ['A','C','G']
}
#再起あり
def dfs(graph,node,visited):
    if node not in visited:
        visited.append(node)
        for n in graph[node]:
            dfs(graph,n,visited)
    return visited

visited=dfs(graph1,'A',[])
print(visited)

#再起なし,スタックで実装
def dfs2(graph,node):
    visited=[node]
    stack=[node]
    while stack:
        #スタックから取り出す
        node=stack[-1]
        if node not in visited:
            visited.extend(node)
        remove_from_stack=True
        for next in graph[node]:
            if next not in visited:
                stack.extend(next)
                remove_from_stack=False
                break
        if remove_from_stack:
            stack.pop()
    return visited
print (dfs2(graph1, 'A'))

['A', 'B', 'S', 'C', 'D', 'E', 'H', 'G', 'F']
['A', 'B', 'S', 'C', 'D', 'E', 'H', 'G', 'F']
